version: "3.9"

services:
  frontend:
    container_name: tunetrail-frontend
    hostname: tunetrail-frontend
    build:
      context: .
      target: dev
      dockerfile: ./docker/frontend/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
  db:
    container_name: tunetrail-db
    hostname: tunetrail-db
    image: postgres:15.2
    platform: linux/amd64
    environment:
      POSTGRES_USER: tunetrail
      POSTGRES_PASSWORD: tunetrail
      POSTGRES_DB: tunetrail
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # dockerコンテナ起動時に自動で実行される.sqlファイル
      - ./backend/_tools/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./backend/_tools/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5555:5432"
    # 設定ファイルを読み込む
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
  grpc:
    container_name: tunetrail-grpc
    hostname: tunetrail-grpc
    build:
      context: .
      target: dev
      dockerfile: ./docker/grpc/Dockerfile
    tty: true
    volumes:
      - ./backend:/app
    ports:
      - 50051:50051
    env_file:
      - ./backend/.env
    depends_on:
      - db
volumes:
  postgres-data:
