version: "3.9"

services:
  frontend:
    container_name: tunetrail-frontend
    hostname: tunetrail-frontend
    build:
      context: .
      target: dev
      dockerfile: ./frontend/Dockerfile
    tty: true
    volumes:
      # `.git` や `*.proto` などもコンテナ内で参照できるようにするため、
      # `/workspace` 直下にリポジトリのルートディレクトリごとマウントする
      - .:/workspace:cached
    ports:
      - 3000:3000
  kvs:
    container_name: tunetrail-kvs
    hostname: tunetrail-kvs
    image: redis:6.2
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  mock:
    container_name: tunetrail-mock
    hostname: tunetrail-mock
    image: node:20.9-bullseye-slim
    volumes:
      - .:/workspace:cached
    ports:
      - 3001:3001
    working_dir: /workspace/frontend
    command: npm run mock
  db:
    container_name: tunetrail-db
    hostname: tunetrail-db
    image: postgres:15.2
    platform: linux/amd64
    environment:
      POSTGRES_USER: tunetrail
      POSTGRES_PASSWORD: tunetrail
      POSTGRES_DB: tunetrail
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # dockerコンテナ起動時に自動で実行される.sqlファイル
      - ./backend/_tools/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./backend/_tools/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5555:5432"
    # 設定ファイルを読み込む
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
  grpc:
    container_name: tunetrail-grpc
    hostname: tunetrail-grpc
    build:
      context: .
      target: dev
      dockerfile: ./backend/Dockerfile
    tty: true
    volumes:
      - .:/workspace:cached
    ports:
      - 50051:50051
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - mock
volumes:
  postgres-data:
  redis-data:
