version: "3.9"

services:
  frontend:
    container_name: tunetrail-frontend
    hostname: tunetrail-frontend
    build:
      context: .
      target: dev
      dockerfile: ./docker/frontend/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
  grpc:
    container_name: tunetrail-grpc
    hostname: tunetrail-grpc
    build:
      context: .
      target: dev
      dockerfile: ./docker/grpc/Dockerfile
    tty: true
    volumes:
      - ./api:/app
    ports:
      - 50051:50051
