name: Test for api

on:
  push:
    branches:
      - "main"
    paths:
      - "**.js"
      - "**.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - .github/workflows/test-js-and-ts.yml
  pull_request:
    paths:
      - "**.js"
      - "**.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - .github/workflows/test-js-and-ts.yml

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ./web/package.json

      - name: install dependencies
        run: npm ci

      # TODO: レポートを出力する
      - name: run tests
        run: npm test
